import { IMAGE_VARIANTS } from "./image-variants";

// Custom next/image loader for the static export. There is no image server on
// GitHub Pages, so srcset candidates point at WebP variants pre-generated by
// scripts/build-images.mjs. Anything without a generated variant (SVG marks,
// widths above the master) resolves to the original file, so a request can
// never produce a URL that does not exist in the build.
export default function kindredImageLoader({ src, width }: { src: string; width: number; quality?: number }): string {
  const entry = IMAGE_VARIANTS[src];
  if (!entry) return src;
  const candidate = entry.widths.find((w) => w >= width);
  if (!candidate) return src; // master is the largest candidate
  return src.replace(/\.webp$/, `-${candidate}.webp`);
}
