// Generated by scripts/build-images.mjs. Do not edit by hand.
// Available pre-generated WebP widths per master image (src/lib/image-loader.ts).
export const IMAGE_VARIANTS: Record<string, { master: number; widths: number[] }> = {
  "/kindred/photos/badge-welcome.webp": {
    "master": 1536,
    "widths": [
      640,
      960,
      1280
    ]
  },
  "/kindred/photos/candid-conversation.webp": {
    "master": 1536,
    "widths": [
      640,
      960,
      1280
    ]
  },
  "/kindred/photos/clinic-reception.webp": {
    "master": 1536,
    "widths": [
      640,
      960,
      1280
    ]
  },
  "/kindred/photos/nurse-portrait.webp": {
    "master": 1024,
    "widths": [
      640,
      960
    ]
  },
  "/kindred/campaign/about-two-colleagues-wide.webp": {
    "master": 1536,
    "widths": [
      640,
      960,
      1280
    ]
  },
  "/kindred/campaign/facility-partner-station.webp": {
    "master": 1536,
    "widths": [
      640,
      960,
      1280
    ]
  },
  "/kindred/campaign/first-shift-welcome.webp": {
    "master": 1536,
    "widths": [
      640,
      960,
      1280
    ]
  },
  "/kindred/campaign/home-hero-handoff.webp": {
    "master": 1536,
    "widths": [
      640,
      960,
      1280
    ]
  }
};
